-- ============================================================
-- CONECTA VAGAS DF — DADOS DE DEMONSTRAÇÃO (seed)
-- ============================================================
-- Importe DEPOIS do database/schema.sql.
-- Contas de teste (troque as senhas antes de publicar):
--   admin@conectavagas.com     / Admin@123
--   empresa@conectavagas.com   / Empresa@123
--   candidato@conectavagas.com / Candidato@123
-- Inclui 14 categorias, 62 vagas (cartazes em public/assets/img/vagas),
-- 5 cursos (capas em public/assets/img/cursos) e a assinatura VIP do candidato de teste.
-- ============================================================

SET NAMES utf8mb4;
USE conecta_vagas_df_v2;

INSERT INTO usuarios(nome,email,senha,tipo,telefone) VALUES
('Administrador','admin@conectavagas.com','$2y$12$6AKJ6lx6.h0haWsmgiDBwe4fMaMjUTlKw5uhg/Qj7Y6mUVgEXrvfu','admin','(61) 99999-9999'),
('Empresa Teste','empresa@conectavagas.com','$2y$12$tzGJeKQV5zNrxYei.3hWeu48g3iywGTSY4Moyn8F/48TiP4/hZYhm','empresa','(61) 98888-8888'),
('Candidato Teste','candidato@conectavagas.com','$2y$12$AKmQPWZpUGx/xu7xB7vZgOdb8vSTl5/tfNuW8buI01Uaehs8APLaa','candidato','(61) 97777-7777');

INSERT INTO perfis(usuario_id,nome_fantasia,setor,cidade,uf,bio,publico,aceite_lgpd,aceite_em,titulo_profissional,nivel_experiencia,habilidades,competencias,objetivo) VALUES
(2,'Empresa Teste','Tecnologia','Brasília','DF','Empresa de teste do ambiente local.',1,1,NOW(),NULL,'junior',NULL,NULL,NULL),
(3,NULL,NULL,'Brasília','DF','Perfil de candidato para testes.',1,1,NOW(),'Candidato em busca de oportunidades','junior','Atendimento, Excel, Tecnologia','Comunicação, organização','Buscar oportunidade profissional no DF.');

INSERT INTO categorias(nome,tipo) VALUES
('Tecnologia da Informação','vaga'),('Administração','vaga'),('Marketing','vaga'),('Vendas','vaga'),('Recursos Humanos','vaga'),('Financeiro','vaga'),('Engenharia','vaga'),('Saúde','vaga'),('Educação','vaga'),
('Informática e Excel','curso'),('Empreendedorismo e Gestão','curso'),('Administração e Atendimento','curso'),('Marketing, Dados e UX','curso'),('Negócios, Finanças e ESG','curso');

SET @perfil_empresa_teste = (SELECT id FROM perfis WHERE usuario_id = 2);

INSERT INTO vagas(perfil_empresa_id,categoria_id,titulo,descricao,requisitos,beneficios,tipo_vaga,nivel_experiencia,remoto,cidade,uf,salario_minimo,salario_maximo,imagem,status,data_publicacao) VALUES
(@perfil_empresa_teste,4,'Atendente / Vendedor / Gerente','Oportunidade para atendimento e vendas em shoppings de Brasília e Aeroporto.','Comunicação, atendimento ao cliente e disponibilidade para escala 6x1.','Salário entre R$ 1.700 e R$ 2.400 + benefícios.','clt','junior','presencial','Brasília','DF',1700,2400,'assets/img/vagas/vaga1.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,8,'Técnico de Enfermagem','Atuação em centro médico no Guará.','Curso técnico e registro profissional conforme a função. Residir no Guará ou proximidades.','Salário compatível + VT.','clt','junior','presencial','Guará','DF',NULL,NULL,'assets/img/vagas/vaga2.png','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedor Interno','Atendimento comercial e vendas internas em Taguatinga.','Comunicação, negociação e foco em resultados.','R$ 3.000 a R$ 5.500 + comissões. 10 vagas.','clt','junior','presencial','Taguatinga','DF',3000,5500,'assets/img/vagas/vaga3.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,2,'Atendente de Loja (6h)','Atendimento em loja em Águas Claras.','Disponibilidade para jornada de 6 horas.','R$ 1.105 + VT + academia + shake proteico.','clt','estagiario','presencial','Águas Claras','DF',1105,1105,'assets/img/vagas/vaga4.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,2,'Motorista','Entregas de hortifrúti com horários flexíveis.','CNH B ou D e disponibilidade para madrugada/manhã.','Horários flexíveis.','clt','junior','presencial','Brasília','DF',NULL,NULL,'assets/img/vagas/vaga5.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,2,'Empregada Doméstica','Atuação em residência em Vicente Pires.','Experiência com rotina doméstica e disponibilidade de segunda a sábado.','R$ 1.621 + VT + alimentação. 7h às 15h.','clt','junior','presencial','Vicente Pires','DF',1621,1621,'assets/img/vagas/vaga6.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,7,'Bombeiro Hidráulico (Obra)','Atuação em obra de grande porte.','Experiência em obras de grande porte.','R$ 2.420 + VT + VR R$ 33,40.','clt','pleno','presencial','Brasília','DF',2420,2420,'assets/img/vagas/vaga7.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,7,'Eletricista de Obra','Atuação em obra no Lago Sul.','Experiência em elétrica predial.','R$ 2.420 + VT + VR R$ 33,40. Segunda a sexta, 7h às 17h.','clt','pleno','presencial','Lago Sul','DF',2420,2420,'assets/img/vagas/vaga8.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Atendente McDonald’s','Atendimento em unidade de Águas Claras.','Disponibilidade para escala 5x2 ou 12x36.','Plano de saúde, odonto, day off e cesta básica.','clt','estagiario','presencial','Águas Claras','DF',NULL,NULL,'assets/img/vagas/vaga9.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,1,'Auxiliar Administrativo','Rotinas administrativas, organização de documentos, controle de planilhas e atendimento telefônico.','Pacote Office, Excel intermediário, boa comunicação e organização.','R$ 1.900 + VT + VR.','clt','junior','presencial','Brasília','DF',1900,1900,'assets/img/vagas/vaga11.png','ativa',CURDATE()),
(@perfil_empresa_teste,1,'Desenvolvedor PHP Júnior','Desenvolvimento e manutenção de sistemas web.','PHP, MySQL, HTML, CSS, JavaScript e Git.','R$ 3.500 a R$ 4.500 + VR + plano de saúde. Modelo híbrido.','clt','junior','hibrido','Brasília','DF',3500,4500,'assets/img/vagas/vaga10.png','ativa',CURDATE());


-- Vagas cadastradas a partir dos cartazes enviados (curadoria; anunciante = empresa do cartaz).
INSERT INTO vagas(perfil_empresa_id,categoria_id,titulo,anunciante,descricao,requisitos,beneficios,contato,tipo_vaga,nivel_experiencia,remoto,cidade,uf,salario_minimo,salario_maximo,imagem,status,data_publicacao) VALUES
(@perfil_empresa_teste,NULL,'Atendente / Garçom',NULL,'GONTIJO',NULL,'VA NO LOCAL, VT E\r\nPLANO ODONTOLÓGICO PELO SINDICATO\r\nPRODUTIVIDADE PARA QUEM NAO FALTAR','WhatsApp (61) 99324-2305','clt','junior','presencial','Guará','DF',NULL,NULL,'assets/img/vagas/vaga24.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Auxiliar de Cozinha','Restaurante Prosa di Minas','Auxiliar de cozinha no Restaurante Prosa di Minas, em Águas Claras. Horário das 8h às 16h, com 1 folga semanal.','Experiência na função\nComprometimento','Salário de R$ 1.859,00\nVale-transporte\nAlimentação no local\n1 folga semanal','WhatsApp (61) 98549-9498 · prosarh2020@gmail.com','clt','junior','presencial','Águas Claras','DF',1859.00,NULL,'assets/img/vagas/vaga25.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Operador de Cópias / Impressões','Papelaria Shalom','A Papelaria Shalom contrata 2 operadores de cópias e impressões no Guará II. Atividades: impressão, cópias, digitalização de documentos e encadernação.','Ensino médio completo\nConhecimento básico em Word e Excel','Salário comercial\nVale-transporte','WhatsApp (61) 99189-1238','clt','junior','presencial','Guará','DF',NULL,NULL,'assets/img/vagas/vaga26.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Churrasqueiro','Casa Gaúcha Restaurante e Churrascaria','1 vaga de churrasqueiro com experiência no SIA. Segunda a sábado, das 7h às 16h.','Experiência como churrasqueiro','Salário a combinar\nVale-transporte\nAlimentação','WhatsApp (61) 99909-9896','clt','pleno','presencial','SIA','DF',NULL,NULL,'assets/img/vagas/vaga27.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedora','Loja de Moda Feminina','Loja de moda feminina em Ceilândia Norte contrata vendedora para vendas e atendimento ao cliente.','Gostar de vendas e atendimento\nSer ágil, comunicativa e organizada\nDisponibilidade de horário',NULL,'WhatsApp (61) 98260-0618','clt','junior','presencial','Ceilândia','DF',NULL,NULL,'assets/img/vagas/vaga28.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Garçom / RH-DP / Operador de Caixa','Mandaka','O Mandaka contrata com início imediato: garçom, assistente de RH/DP e operador de caixa. Lojas em Taguatinga Sul, Águas Claras e Guará II.','Experiência na função\nResidir no DF\nDisponibilidade de horário','Salário + produtividade + gorjeta\nRefeição no local\nFiliação a clubes\nClínica médica e saúde mental\nPlano odontológico gratuito\nPlano de medicamentos','WhatsApp (61) 99350-6572 · vagastrabalho27@gmail.com','clt','junior','presencial','Taguatinga','DF',NULL,NULL,'assets/img/vagas/vaga29.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,2,'Estágio em Administração / RH','Restaurante Self-Service Asa Norte','Restaurante self-service na Asa Norte contrata estagiários de Administração, Recursos Humanos, Tecnólogos em Gestão e cursos afins. Horário das 10h às 16h, com folga fixa na semana ou escala ajustada ao curso.','Cursar Administração, RH, Tecnólogo em Gestão ou curso afim','Bolsa a partir de R$ 1.200,00 líquidos\nVale-transporte\nAlmoço no local\nSeguro de vida','WhatsApp (61) 99620-1679','estagio','estagiario','presencial','Asa Norte','DF',1200.00,NULL,'assets/img/vagas/vaga30.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Jovem Aprendiz — Posto de Combustíveis','Cascol','Jovem aprendiz para atuar em posto de combustíveis: atendimento ao público e apoio às rotinas operacionais do posto. Regiões: Taguatinga, Ceilândia, Guará, Paranoá, São Sebastião, Varjão, Sobradinho e Planaltina.','18 anos completos\nDisponibilidade para jornada de 6 horas',NULL,'WhatsApp (61) 98625-7024','clt','estagiario','presencial','Taguatinga','DF',NULL,NULL,'assets/img/vagas/vaga31.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Atendente','Subway (Grupo Elizete)','O Subway contrata atendente para as lojas de Taguatinga Sul, Ceilândia Norte e M Norte.','Ensino médio completo\nProatividade\nBoa comunicação\nVontade de aprender\nDisponibilidade de horário',NULL,'vagasgrupoelizete@gmail.com · WhatsApp (61) 98402-4592','clt','junior','presencial','Taguatinga','DF',NULL,NULL,'assets/img/vagas/vaga32.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedor(a)','Alô Celulares','Vendas e atendimento ao cliente em loja de acessórios para celulares, capas, películas e produtos de informática no Shopping Conjunto Nacional. Escala 6x1, das 14h às 22h. No e-mail, informe \"Vendedor(a) Conjunto Nacional\".','Experiência com vendas será um diferencial','Salário de R$ 1.790,26\nBonificação por vendas\nVale-transporte','alocelulares.curriculos@gmail.com · Jéssica (61) 99839-0202','clt','junior','presencial','Brasília','DF',1790.26,NULL,'assets/img/vagas/vaga33.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Copeira','Casa do Vovô','A Casa do Vovô, em Vicente Pires, contrata copeira. Escala 12x36 (trabalha um dia e folga no outro); horas extras pagas quando realizadas.',NULL,'Salário bruto inicial de R$ 1.707,54\nVale-transporte\nCafé da manhã e lanche da tarde\nAlmoço: cesta básica mensal ou marmita diária\nParceria com a Anhanguera (descontos em graduação, extensivos aos familiares)','contato.rh.csv@gmail.com','clt','junior','presencial','Vicente Pires','DF',1707.54,NULL,'assets/img/vagas/vaga34.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Zelador / Encarregado de Serviços Gerais','Casa do Vovô','A Casa do Vovô, em Vicente Pires, contrata zelador / encarregado de serviços gerais. Segunda a sábado; horas extras pagas quando realizadas.','Curso de Agente de Limpeza','Salário a combinar\nVale-transporte\nCafé da manhã e lanche da tarde\nAlmoço: cesta básica mensal ou marmita diária\nParceria com a Anhanguera (descontos em graduação, extensivos aos familiares)','contato.rh.csv@gmail.com','clt','junior','presencial','Vicente Pires','DF',NULL,NULL,'assets/img/vagas/vaga35.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Atendente de Lanchonete','Giraffas','O Giraffas contrata atendente de lanchonete para o Shopping Boulevard, na Asa Norte. Escala 12x36, das 10h às 22h.',NULL,'Salário comercial\nVale-transporte\nAlimentação no local\nProdutividade','WhatsApp (61) 98473-6782','clt','junior','presencial','Asa Norte','DF',NULL,NULL,'assets/img/vagas/vaga36.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedor(a) — Cenografia e Estandes','Empresa de Cenografia e Eventos','Empresa de cenografia, estandes, mobiliário, palcos, balcões de credenciamento e comunicação visual para feiras, congressos e eventos corporativos em Brasília. CLT (contrato de experiência), 44 horas semanais presenciais nas unidades do SAAN e do CICB, incluindo sábado pela manhã.','Prospecção e organização do funil de vendas\nAgilidade e foco em resultados','Salário fixo de R$ 2.500,00 + comissão sobre vendas, sem teto\nAuxílio-refeição de R$ 29,03 por dia útil (cerca de R$ 638/mês)\nVale-transporte\nSeguro de vida\nDemais benefícios da convenção coletiva','Ysadora — WhatsApp (21) 97492-4014','clt','junior','presencial','Brasília','DF',2500.00,NULL,'assets/img/vagas/vaga37.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Embaixador(a) da Experiência do Cliente','McDonald’s Asa Sul','Cuidar da jornada do cliente do início ao fim da visita, com atenção, respeito e o melhor atendimento. McDonald’s da quadra 404/405 da Asa Sul. Escala 6x1, das 16h às 00h. Ao enviar o currículo, informe que é para a vaga de Embaixador.','Maior de 18 anos\nFacilidade de acesso ao restaurante','Salário bruto de R$ 2.239,00\nPlano de saúde\nPlano odontológico\nSeguro de vida\nRefeição no local\nVale-transporte\nGympass\nBolsas de estudo\nPlano de carreira','WhatsApp (61) 99801-5842','clt','junior','presencial','Asa Sul','DF',2239.00,NULL,'assets/img/vagas/vaga38.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Auxiliar de Cozinha / Chapeiro / Garçom','A Banka','A Banka, no Cruzeiro Velho, contrata auxiliar de cozinha, chapeiro e garçom. Funções: apoio na cozinha, preparo e organização dos alimentos, limpeza e higienização, atendimento e suporte à equipe. Segunda a sábado, das 8h às 16h30, com folga todos os domingos.','Experiência na função\nMorar no DF\nComprometimento e pontualidade\nTrabalho em equipe','Salário base de R$ 1.750 a R$ 2.200, conforme a função\nVale-transporte\nVale-alimentação no local\nProdutividade\nComissão global','WhatsApp (61) 98201-7405','clt','junior','presencial','Cruzeiro','DF',1750.00,2200.00,'assets/img/vagas/vaga39.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,2,'Motorista de Caminhão','UAÇO','A UAÇO contrata motorista de caminhão no Setor de Indústria de Ceilândia.','CNH categoria C\nDisponibilidade para viagens','Salário acima da categoria\n10% de assiduidade\nVale-refeição\nCesta básica\nVale-transporte','curriculos.uacobrasil@gmail.com · WhatsApp (61) 99000-2115','clt','junior','presencial','Ceilândia','DF',NULL,NULL,'assets/img/vagas/vaga40.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,5,'Auxiliar / Assistente de DP-RH','Empresa privada em Santa Maria','Contratação para departamento pessoal, RH e parte fiscal (auxiliar, assistente ou analista), com início imediato. Atividades: rotinas de Departamento Pessoal e Recursos Humanos. Agende a entrevista com Estefâne pelo telefone.','Experiência em DP/RH\nConhecimento em legislação tributária e obrigações acessórias (PIS/COFINS, ICMS, ISS)\nDisponibilidade para início imediato','Salário de R$ 2.000,00\nVale-transporte (passagem até R$ 10,00)\nVale-alimentação de R$ 20,00','Estefâne — (61) 9904-3008','clt','pleno','presencial','Santa Maria','DF',2000.00,NULL,'assets/img/vagas/vaga41.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Consultor(a) de Vendas','Vivo — Parceiro 4R','Venda de serviços de telefonia e dados, esclarecimento de informações técnicas e suporte aos clientes na escolha da solução adequada, com atuação em sondagem, prospecção e pós-venda. Vaga em Águas Lindas (GO), também para PCD.','Ensino médio completo\nDisponibilidade de horário\nComunicação\nResponsabilidade\nFoco em resultados\nInteresse por tecnologia','Salário fixo de R$ 1.621,00\nVale-alimentação de R$ 20,00/dia\nVale-transporte\nComissão de vendas e premiações por meta\nSeguro de vida\nPlano de carreira\nPlano odontológico\nDescontos em farmácias\nCartão de benefícios\nTotalPass\nDay off\nTelemedicina','WhatsApp (61) 99698-1058','clt','junior','presencial','Águas Lindas','GO',1621.00,NULL,'assets/img/vagas/vaga42.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Estágios: Atendente, Vendas, Secretária(o) e Refrigeração','Zane Estágios','5 oportunidades de estágio em Brasília/DF:\n1. Atendente — Asa Norte — R$ 800 + VT + VA — seg. a sáb., 30h semanais\n2. Atendente de loja — Asa Norte — R$ 1.000 + comissão — seg. a sex.\n3. Atendimento e vendas — Gama Shopping — R$ 900 + comissão por metas — seg. a sáb., 5h diárias\n4. Secretária(o) — Cruzeiro — R$ 900 + VT — seg. a sáb., 9h às 15h\n5. Auxiliar de refrigeração — Cruzeiro — R$ 900 + VT — seg. a sex. 9h–15h, sáb. 8h–12h','Estar estudando (vaga de estágio)\nAuxiliar de refrigeração: noções básicas de refrigeração','Bolsa de R$ 800 a R$ 1.000\nVale-transporte (conforme a vaga)\nComissão nas vagas de loja e vendas','WhatsApp (61) 99318-0769','estagio','estagiario','presencial','Asa Norte','DF',800.00,1000.00,'assets/img/vagas/vaga43.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Trainee de Vendas','JOVI','7 vagas de trainee de vendas, CLT, em Brasília/DF. Responsabilidades: apoiar vendas, atender clientes, prospectar oportunidades, apoiar propostas e negociações, acompanhar metas e indicadores e participar de treinamentos e projetos. No e-mail, use o título \"Trainee de Vendas\".','Inglês fluente/avançado (conversação e escrita) — obrigatório\nGraduação completa em qualquer área\nRecém-formado(a)\nPacote Office intermediário\nPerfil proativo e vontade de aprender','Salário de R$ 2.200,00\nVale-alimentação de R$ 40,00 por dia\nCartão mobilidade de R$ 400,00\nPlano de saúde e odontológico Bradesco\nSeguro de vida','mwhr@jovimobile.com · (61) 98175-0661','clt','junior','presencial','Brasília','DF',2200.00,NULL,'assets/img/vagas/vaga44.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Atendente','Panificadora Gonçalina','A Panificadora Gonçalina contrata atendente. Vagas para o SIA e Ceilândia. Deixe o currículo na loja ou envie por e-mail.',NULL,'Regime CLT\nVale-transporte\nSalário e horário a combinar','goncalinarh@gmail.com · (61) 99404-2674','clt','junior','presencial','Ceilândia','DF',NULL,NULL,'assets/img/vagas/vaga45.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Diversas vagas: Operador de Loja, Auxiliares e Estagiários','Cinco Estrelas Casa de Pães','A Cinco Estrelas Casa de Pães, com mais de 30 anos de mercado, tem vagas em aberto: Nutricionista (1), Auxiliar de Cozinha (1), Auxiliar de Produção (2), Estagiário de Nutrição (2), Estagiário de Produção (5), Estagiário de Loja (10), Estagiário de RH (1), Auxiliar de Serviços Gerais (1), Operador de Loja (10) e Motoboy (1). Unidades: Ceilândia (Setor O), Guará I e II, Asa Sul, Sudoeste, Noroeste e Águas Claras. Envie o currículo com o cargo pretendido. Todas as vagas são abertas para PCD.',NULL,'Alimentação no local (Setor O) ou vale-alimentação (operador de loja 12x36)\nVale-transporte com crédito quinzenal\nVenda a prazo: 10% do salário em produtos da loja + 5% de desconto\nDay off no mês do aniversário\nParcerias com faculdades\nPlano de saúde PRIME-X: R$ 49,90 para toda a família\nOportunidades de crescimento interno','rh.cecp@gmail.com · (61) 98626-0256','clt','junior','presencial','Ceilândia','DF',NULL,NULL,'assets/img/vagas/vaga46.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Auxiliar de Cozinha','Grupo Dourado','Auxiliar de cozinha em Águas Claras, 2 vagas. Das 14h20 às 22h, CLT 6x1.',NULL,'Salário a partir de R$ 1.900,00\nVale-transporte\nAlimentação no local\nPremiação mensal\nTreinamento especializado','grupodouradooo@gmail.com · (11) 98855-1331','clt','junior','presencial','Águas Claras','DF',1900.00,NULL,'assets/img/vagas/vaga47.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedor(a)','World Tennis','A World Tennis contrata vendedor(a) para as lojas do Taguatinga Shopping, JK Shopping, Park Shopping, Conjunto Nacional, Pátio Brasil e Shopping Sul.',NULL,NULL,'curriculowt@gmail.com · WhatsApp (61) 99886-5320','clt','junior','presencial','Brasília','DF',NULL,NULL,'assets/img/vagas/vaga48.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Diarista','Tô Mais Vip Diaristas','30 vagas de diarista com trabalho fixo e pagamento todo dia 15. Ganho inicial de R$ 2.611,00/mês (R$ 2.369,00 de pagamento + R$ 242,00 de transporte).',NULL,'Pagamento mensal de R$ 2.369,00 (todo dia 15)\nTransporte de R$ 242,00/mês (R$ 11,00/dia, Cartão BRB Mobilidade)\nPremiação anual\nPremiações extras (Dia da Mulher, Páscoa, Natal etc.)\nDay off no Natal, Ano Novo e aniversário\nIndicação premiada: R$ 300,00 no 6º mês + R$ 50,00 por mês por indicação ativa','WhatsApp (61) 8182-2325','clt','junior','presencial','Brasília','DF',2369.00,NULL,'assets/img/vagas/vaga49.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Consultor(a) de Venda Interna','Concluinte','A Concluinte (concluinte.com.br · @concluinteead) contrata consultor(a) de venda interna em Taguatinga Sul.','Experiência na área\nBoa comunicação verbal e escrita\nCriatividade','Salário de R$ 1.621,00\nComissão de até 20%\nBonificação mensal\nPremiação diária\nPassagens','WhatsApp (61) 98122-6097','clt','junior','presencial','Taguatinga','DF',1621.00,NULL,'assets/img/vagas/vaga50.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,8,'Atendente de Farmácia','Farmácia (rede em expansão)','Atendente de farmácia, escala 5x2. Empresa em processo de expansão, com oportunidades de crescimento interno.','Disponibilidade para fechamento\nBoa comunicação\nAtendimento ao público','Vale-alimentação\nVale-transporte\nPlano odontológico\nConvênio farmácia\nTelemedicina\nPlataforma de cursos\nParcerias com faculdades\nApoio psicológico\nAcompanhamento nutricional\nTrilha de carreira','(61) 99530-4348','clt','junior','presencial','Brasília','DF',NULL,NULL,'assets/img/vagas/vaga51.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Promotor de Vendas com Moto','Sama','Promotor com moto, CLT efetivo, início imediato. Segunda a sexta, das 7h às 16h48 (não trabalha sábado e domingo). Roteiro: São Sebastião, Itapoã, Lago Sul e Paranoá. Atividades: abastecimento, layout e precificação de produtos, controle de validade, organização de gôndolas e conquista de pontos extras. No WhatsApp, informe \"Promotor de Vendas\".','Residir no Paranoá, São Sebastião ou Itapoã\nEnsino médio completo\nMoto e CNH categoria A (documentação em dia)\nExperiência com abastecimento, precificação, organização e validade de produtos','Salário de R$ 1.658,80\nAdicional de periculosidade de R$ 497,00\nVale-refeição de R$ 31,00 por dia\nReembolso de R$ 0,65 por km\nAuxílio smartphone de R$ 100,00\nSeguro de vida em grupo','WhatsApp (61) 99127-7683','clt','junior','presencial','Paranoá','DF',1658.80,NULL,'assets/img/vagas/vaga52.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Operador de Caixa / Operador de Loja (temporário)','Sama','Ação Dia das Crianças – Ato II: contrato temporário de 29/09 a 15/10/2026 (17 dias, sendo 15 trabalhados), das 14h às 22h. Locais: Shopping Iguatemi, Taguatinga Shopping, Parque Shopping, Gilberto Salomão, SIA, Aeroporto e Águas Claras. Entrevista presencial na quinta-feira, 24/09, às 14h, na Agência Sama (EPNB, sentido Samambaia–Plano Piloto, em frente ao Costa Atacadista). Leve o currículo impresso.','Ser maior de 18 anos\nDisponibilidade das 14h às 22h\nExperiência com atendimento ao público\nInício imediato\nDisponibilidade para hora extra','Ganho total estimado de R$ 2.250,40 no período\nSalário do período de R$ 1.235,52 (base de R$ 2.180,33)\n13º, férias e 1/3 proporcionais\nVale-transporte de R$ 165,00\nVale-refeição de R$ 31,00/dia (R$ 465,00 no período)\nPossibilidade de horas extras','(61) 3386-4585','temporario','junior','presencial','Brasília','DF',2250.40,NULL,'assets/img/vagas/vaga53.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedor Externo (Porta a Porta)','Fênix Telecom','15 vagas externas de vendedor porta a porta de pacotes de telefonia, banda larga e TV em Brasília e Águas Lindas. Somente moradores de Brasília e Águas Lindas. Falar com Fernanda ou André.','Boa comunicação\nExperiência na área\nProatividade','Salário de R$ 1.790,26\nVale-refeição de R$ 21,00/dia\nVale-transporte de R$ 11,00/dia\nComissões agressivas','WhatsApp (61) 99413-1811','clt','junior','presencial','Brasília','DF',1790.26,NULL,'assets/img/vagas/vaga54.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Atendente McDonald’s (Ceilândia)','McDonald’s (Grupo Levvo)','Novos horários no McDonald’s de Ceilândia: almoço, jantar e madrugada (11h45 às 21h, 14h às 23h ou 20h às 5h). Escala 5x2 ou 12x36.',NULL,'Salário de R$ 1.778,94\nPlano de saúde e odontológico\nTotalPass (desconto em academias)\nAuxílio cesta básica\nPlano de carreira\nPremiação por tempo de empresa\nDay off','WhatsApp (61) 99682-7682 · contrata@grupolevvo.com.br','clt','junior','presencial','Ceilândia','DF',1778.94,NULL,'assets/img/vagas/vaga55.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Serviços Gerais, Caixa, Cozinha, Pizzaria, Bar e Cumim','Don Romano Cantina & Pizzaria','Vagas: auxiliar de serviços gerais, operador de caixa, auxiliar de cozinha, auxiliar de pizzaria, auxiliar de bar e cumim. Unidades no Lago Sul, Águas Claras e Asa Norte. Envie o currículo com o nome da vaga pretendida.','Ser maior de 18 anos\nMorar no DF\nDisponibilidade de horário','Salário de R$ 1.750,68 + 5% de produtividade + gorjetas\nVale-transporte\nAlimentação no local\nAssistência médica e odontológica (sindicato)\nConvênio com Aqua Cerrado e SESC','selecaorestaurantelagosul@gmail.com · WhatsApp (61) 3968-6670','clt','junior','presencial','Lago Sul','DF',1750.68,NULL,'assets/img/vagas/vaga56.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Assistente de Vendas Online e E-commerce','Loja de e-commerce (Núcleo Bandeirante)','2 vagas, modelo híbrido (5 dias presenciais + 1 remoto) no Núcleo Bandeirante. Terça a sexta, das 9h às 18h, e sábado, das 9h às 13h. Entrevistas online. Atividades: atendimento e suporte às vendas online, gestão das redes sociais, anúncios em marketplaces (Mercado Livre e OLX), cadastro de produtos no ERP Bling, fotografia e edição básica de imagens, conferência dos anúncios e acompanhamento das vendas.','Experiência em vendas\nConhecimento básico de informática\nProatividade e vontade de aprender\nDiferencial: conhecimento ou experiência com o ERP Bling','Salário de R$ 1.800,00 + comissão','WhatsApp (61) 98264-9322 · https://w.app/gcy48w','clt','junior','hibrido','Núcleo Bandeirante','DF',1800.00,NULL,'assets/img/vagas/vaga57.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,2,'Auxiliar de Depósito','Santa Therezinha','Auxiliar de depósito, escala 5x2 (segunda a sexta). Candidatos de Ceilândia, Taguatinga ou Águas Lindas.',NULL,'Comissão por produtividade de até R$ 1.000\nVale-alimentação de R$ 25,00 por dia trabalhado\nConvênio com faculdades\nConvênio com o SESC\nPlano de saúde Hapvida\nBônus por qualidade e desempenho\nCesta básica\nPlano odontológico\nDescontos em academias\nTransporte da empresa\nPrograma de crescimento de carreira','WhatsApp (61) 99466-7123','clt','junior','presencial','Ceilândia','DF',NULL,NULL,'assets/img/vagas/vaga58.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Analista de Retenção (Cancelamento)','Indeniza Proteção Veicular','Atender clientes que pedem cancelamento, entender o motivo, negociar e apresentar alternativas para a permanência, com foco em reverter cancelamentos. Segunda a sexta, das 8h30 às 18h, em Taguatinga.','Comunicação e persuasão\nAgilidade e proatividade\nBoa negociação\nFoco em resultados\nSaber contornar objeções e resolver conflitos','Salário fixo\nVale-alimentação\nVale-transporte\nComissão por reversão','WhatsApp (61) 99367-6616','clt','junior','presencial','Taguatinga','DF',NULL,NULL,'assets/img/vagas/vaga59.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,6,'Operador de Cobrança','Santos Beneli Advogados','Operador de cobrança presencial em Brasília/DF, regime CLT. No assunto do e-mail, informe \"Operador de cobrança\".','Boa comunicação\nFoco em resultados\nVontade de crescer','Salário de R$ 1.744,75\nVale-transporte\nVale-alimentação\nConvênio com o SESC','rh@santosbeneli.com.br · WhatsApp (11) 94666-0470','clt','junior','presencial','Brasília','DF',1744.75,NULL,'assets/img/vagas/vaga60.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Auxiliar de Limpeza','Cantón Restaurante','O Cantón Restaurante (Peruvian Chinese Food) está aumentando o time e contrata auxiliar de limpeza no Venâncio Shopping, em Brasília. Escala 6x1.','Responsabilidade e comprometimento\nAgilidade\nGostar de trabalhar em equipe','Salário-base de R$ 1.750,00\n5% de produtividade\nComissão variável conforme as vendas do restaurante\nVale-transporte','WhatsApp (61) 99334-0848','clt','junior','presencial','Brasília','DF',1750.00,NULL,'assets/img/vagas/vaga78.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Auxiliar de Cozinha','Restaurante no Cruzeiro Novo','Vaga aberta para auxiliar de cozinha em loja no Cruzeiro Novo. Das 14h30 às 22h30, escala 5x2 com 2 folgas semanais. Atividades: auxílio no preparo, cocção, finalização e montagem; organização e limpeza da cozinha e das áreas de produção; apoio na lista de compras.','Comprometimento com o padrão da marca\nBoa comunicação\nTrabalho em equipe\nExperiência na área é um diferencial','Salário base de R$ 1.800,00\nBônus em dinheiro por metas alcançadas\nVale-transporte\nAlimentação no local\nAdicional noturno','WhatsApp (61) 99140-2285','clt','junior','presencial','Cruzeiro','DF',1800.00,NULL,'assets/img/vagas/vaga79.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Cozinheira(o)','Cozinha Industrial de Marmitas Saudáveis','Cozinha industrial especializada em marmitas saudáveis, com produção em Taguatinga Norte. Segunda a sexta, das 8h às 18h. Envie o currículo somente se morar em Taguatinga, Ceilândia, Samambaia, Riacho Fundo, Recanto das Emas ou Águas Lindas. No WhatsApp, use o assunto \"Cozinheira(o)\".','Experiência comprovada\nManipulação de alimentos\nHigiene e segurança\nOrganização\nLimpeza\nAgilidade','Remuneração de R$ 2.600,00','WhatsApp (61) 99379-0143','clt','pleno','presencial','Taguatinga','DF',2600.00,NULL,'assets/img/vagas/vaga80.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Auxiliar de Serviços Gerais','Grupo Bueno','Auxiliar de serviços gerais no Setor de Cargas (DF). Atividades: limpeza interna e externa do ambiente, descarte de lixo, preparo de café para funcionários e clientes da loja, higienização dos banheiros, uso de produtos de limpeza e zelo pela organização do espaço comum.','Conhecimento dos materiais de limpeza em geral\nExperiência como auxiliar de serviços gerais ou diarista é um diferencial','Salário de R$ 1.621,00 (CLT)\nVale-transporte\nVR/VA\nCesta básica\nPlano de saúde\nPlano odontológico\nWellhub (Gympass)\nStarbem\nConvênio com o SESC\nDesconto em peças\nProcessos seletivos internos','WhatsApp (61) 8458-0064','clt','junior','presencial','Brasília','DF',1621.00,NULL,'assets/img/vagas/vaga81.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Atendente McDonald’s (Taguatinga Centro)','McDonald’s Taguatinga Centro','Atendentes para o McDonald’s de Taguatinga Centro. Turnos disponíveis:\n• Diurno (6x1): 7h às 15h ou 10h às 18h\n• Noturno (6x1 e 5x2): 14h às 22h ou 23h, 15h às 23h ou 00h, 16h à 00h\n• Madrugada (5x2): 20h às 5h ou escala mista (2 dias noturno e 3 dias madrugada)','18 anos ou mais\nEnsino médio completo\nDisponibilidade para trabalhar em feriados e fins de semana','Plano de saúde\nPlano odontológico\nPlano de carreira\nSeguro de vida\nRefeição no local\nParceria com academias\nVale-transporte\nParticipação nos lucros','WhatsApp (61) 98487-2054','clt','junior','presencial','Taguatinga','DF',NULL,NULL,'assets/img/vagas/vaga82.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Vendedor(a)','Nação Fla Brasília','3 vagas para vendedor na loja da CLS 308, bloco D, loja 30, Asa Sul. Atividades: atendimento em vendas ágil e cordial, recebimento e conferência de mercadorias, reposição de mercadorias e organização do estoque.','Experiência na área','Salário de R$ 1.790,26\nComissão por meta\nVale-transporte','(61) 99847-9793','clt','junior','presencial','Asa Sul','DF',1790.26,NULL,'assets/img/vagas/vaga83.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,8,'Estágio em Enfermagem','Clínica em Taguatinga (cód. 1308)','Estágio em enfermagem (cód. 1308) em Taguatinga. Segunda a sexta, das 8h às 13h, e sábado, das 8h às 13h. Atividades: coleta de sangue, triagem de pacientes, apoio nos atendimentos de enfermagem e auxílio nas rotinas do setor.','Cursando Enfermagem a partir do 3º semestre\nResidir próximo à região de Taguatinga\nDisponibilidade para o horário informado','Bolsa-auxílio de R$ 750,00\nVale-transporte','WhatsApp (61) 99851-0917','estagio','estagiario','presencial','Taguatinga','DF',750.00,NULL,'assets/img/vagas/vaga84.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Camareiro(a)','Hotel Garden Norte','O Hotel Garden Norte tem vaga para camareiro(a). Escala 12x36, diurno ou noturno, com início imediato.','Habilidade na função igual ou similar\nNoção básica de informática\nOrganização e proatividade\nComprometimento','Ambiente organizado\nEquipe valorizada\nRespeito e confiança','hgempregos@gmail.com · WhatsApp (61) 99575-3710','clt','junior','presencial','Brasília','DF',NULL,NULL,'assets/img/vagas/vaga85.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Operador(a) de Loja','Sam’s Club Águas Claras','O Sam’s Club de Águas Claras contrata operador(a) de loja. Escala 6x1. Local: Rua Copaíba, s/n, LG 01, Mezanino 1B, Loja 2B – Águas Claras. Vagas limitadas.',NULL,'Salário de R$ 1.700,00\nVale-transporte\nAlimentação no local\nPlano de saúde\nPlano odontológico\nPLR – Participação nos Lucros e Resultados\nSeguro de vida\nConvênio com a Rede SESC\nTotalPass','silvanisidorio@gmail.com · WhatsApp (61) 99133-6108','clt','junior','presencial','Águas Claras','DF',1700.00,NULL,'assets/img/vagas/vaga86.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,12,'Auxiliar de Cozinha','Kairós Restaurante','Auxiliar de cozinha no Kairós Restaurante, em Águas Claras. Segunda a sábado, das 8h às 16h. Atividades: auxiliar na parte quente e nas saladas, verificar e auxiliar nas reposições do buffet, auxiliar no preparo de marmitas e na limpeza geral da cozinha. No WhatsApp, use o assunto \"Aux. cozinha\".','Ensino médio completo\nPreferencial: experiência com parte quente e saladas em restaurante','Salário de R$ 1.750,68\n5% de produtividade\nVale-transporte\nAlimentação no local','WhatsApp (61) 98289-3477','clt','junior','presencial','Águas Claras','DF',1750.68,NULL,'assets/img/vagas/vaga87.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Consultor de Vendas (Closer)','Mimória Business','Consultor de vendas (closer) na Asa Sul, Plano Piloto. Contratação PJ/MEI, de segunda a sexta, das 9h às 19h.','Ensino médio completo\nExperiência em vendas consultivas\nBoa comunicação\nHabilidade de negociação\nOrganização e foco em resultados\nDesejável: proatividade, persuasão, inteligência comercial, empatia, escuta ativa e compromisso com metas','Salário fixo de R$ 2.000,00\nComissão agressiva: possibilidade de chegar a R$ 5.000,00\nParticipação em plano de saúde/odontológico\nPlano de carreira','mimoriabusiness@gmail.com · (61) 98888-805','pj','junior','presencial','Asa Sul','DF',2000.00,5000.00,'assets/img/vagas/vaga88.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Consultora de Vendas','Viva Laser','Consultora de vendas em Brasília/DF, 44 horas semanais, das 9h às 19h. Atividades: atendimento presencial e por WhatsApp, acolhimento de clientes, conversão de avaliações, agendamentos, acompanhamento, fidelização, metas e indicadores. Envie currículo e Instagram pelo WhatsApp.','Comunicativa, persuasiva e comercial\nOrganizada, responsável e proativa\nExperiência com vendas será um diferencial','Salário de R$ 1.800,00 + comissão\nPossibilidade de ganhar R$ 3.000,00 ou mais\nVale-transporte\nVale-alimentação de R$ 27 por dia','WhatsApp (61) 99190-5286','clt','junior','presencial','Brasília','DF',1800.00,3000.00,'assets/img/vagas/vaga89.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Promotor de Vendas Exclusivo (com moto)','Prime Trade Marketing','Promotor de vendas exclusivo no Gama, período integral. Necessário ter moto. Atividades: organização e exposição de produtos, layout, envio diário de informações via WhatsApp e cumprimento de roteiro previamente definido.','Ter moto','Remuneração de R$ 2.112,73 (já com 30% de periculosidade)\nAjuda de custo\nVale-alimentação de R$ 25,00\nTotalPass\nDesconto em farmácia\nPAE (Programa de Assistência ao Empregado)','WhatsApp (61) 99281-5941','clt','junior','presencial','Gama','DF',2112.73,NULL,'assets/img/vagas/vaga90.jpg','ativa',CURDATE()),
(@perfil_empresa_teste,4,'Promotor de Vendas','TIME Trade Marketing','Promotor de vendas no Gama, período integral (8h às 17h). Atividades: organização e exposição de produtos, layout, envio diário de informações, cumprimento de roteiro previamente definido e informações diárias via WhatsApp.',NULL,'Salário de R$ 1.625,18\nVale-transporte de acordo com a rota\nVale-alimentação de R$ 25,00\nTotalPass\nDesconto em farmácia\nPAE (Programa de Assistência ao Empregado)','WhatsApp (61) 99281-5941','clt','junior','presencial','Gama','DF',1625.18,NULL,'assets/img/vagas/vaga91.jpg','ativa',CURDATE());

INSERT INTO cursos(categoria_id,titulo,descricao,tipo,modalidade,nivel,duracao,gratuito,preco,url,imagem,instituicao) VALUES
(10,'Informática / Excel / Adm','Cursos 100% gratuitos com certificado.','curso','ead','iniciante','Variável',1,0,'https://www.ev.org.br','assets/img/cursos/curso1.png','Fundação Bradesco – Escola Virtual'),
(11,'Empreendedorismo / Gestão','Capacitação para pequenos negócios e gestão empresarial.','curso','ead','iniciante','Variável',1,0,'https://www.sebrae.com.br','assets/img/cursos/curso2.png','SEBRAE'),
(12,'Administração / Atendimento / Saúde','Cursos online e gratuitos para desenvolvimento profissional.','curso','ead','iniciante','Variável',1,0,'https://www.escolavirtual.gov.br','assets/img/cursos/curso3.png','Escola Virtual do Governo'),
(13,'Marketing Digital / Dados / UX','Cursos e ferramentas de aprendizagem para carreira digital.','curso','ead','iniciante','Variável',1,0,'https://grow.google/intl/pt/courses-and-tools/','assets/img/cursos/curso4.png','Google Grow'),
(14,'Negócios / Finanças / ESG','Cursos gratuitos e opções de formação em negócios.','curso','ead','intermediario','Variável',1,0,'https://portal.fgv.br/cursos-gratuitos','assets/img/cursos/curso5.png','FGV Online');

INSERT INTO assinaturas(usuario_id,plano,valor,data_inicio,data_fim,status) VALUES
(3,'assinante',9.90,CURDATE(),DATE_ADD(CURDATE(), INTERVAL 30 DAY),'ativa');
